model_params:
  model: compcos
  dropout: true
  norm: true
  nlayers: 2    # Default: 2
  relu: false
  fc_emb: 768,1024,1200
  emb_dim: 512
  # emb_dim: 1395
  emb_init: clip
  image_extractor: resnet18
  train_only: false
  static_inp: false

training:
  # batch_size: 128
  # test_batch_size: 64
  batch_size: 32       # For testing
  test_batch_size: 32  # For testing
  load:
  lr: 5.0e-05       # Default: 5.0e-05
  lrg: 1.0e-03      # Default: 1.0e-03
  wd: 5.0e-05       # Default 5.0e-05
  margin: 0.4
  cosine_scale: 20  # Default 20
  max_epochs: 300
  norm_family: imagenet
  save_every: 10
  test_set: val
  topk: 1
  workers: 0
  update_features: false  # temp, should be `false`
  freeze_features: false
  epoch_max_margin: 15
  cpu_eval: false # Temp

optimizer:
  epsilon: 10.e-08
  weight_decay: 0.2
  learning_rate: 5.0e-05

scheduer:
  cycle_mult: 1.0
  warmup_steps: 10